"""Seed data definitions (separate from runtime)."""

SERVICES_SEED = [
    {
        "slug": "mini-soccer", "title": "Mini Soccer Field",
        "short_desc": "Premium mini soccer field construction with FIFA-quality synthetic turf.",
        "full_desc": "Complete construction of mini soccer fields with international-grade synthetic grass, professional drainage systems, and stadium lighting.",
        "icon": "Trophy",
        "image": "https://images.unsplash.com/photo-1546717003-caee5f93a9db?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "45-60 days", "starting_price": "Rp 850 jt",
        "materials": ["50mm Monofilament Turf", "Rubber Granule Infill", "Shock Pad Base", "LED Stadium Lighting"],
        "workflow": ["Site Survey", "Excavation & Leveling", "Drainage Installation", "Sub-base Compaction", "Turf Installation", "Line Marking", "Final Inspection"],
        "features": ["FIFA Quality 1 Star", "10-year warranty", "Drainage system included", "All-weather playability"],
        "order_idx": 1,
    },
    {
        "slug": "futsal", "title": "Futsal Court",
        "short_desc": "Indoor and outdoor futsal court construction with vinyl, interlock or synthetic turf.",
        "full_desc": "Professional futsal court construction featuring premium flooring options, line markings, and goal installations to international standards.",
        "icon": "Goal",
        "image": "https://images.unsplash.com/photo-1550881111-7cfde14b8073?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "30-45 days", "starting_price": "Rp 350 jt",
        "materials": ["Vinyl Sports Flooring", "Interlock Tiles", "20mm Synthetic Turf", "Galvanized Goal Posts"],
        "workflow": ["Site Assessment", "Floor Preparation", "Base Layer", "Surface Installation", "Marking & Coating", "Equipment Setup"],
        "features": ["AMF certified surfaces", "5-year warranty", "Shock absorbent", "Anti-slip finish"],
        "order_idx": 2,
    },
    {
        "slug": "basketball", "title": "Basketball Court",
        "short_desc": "Professional basketball court construction with acrylic sports flooring system.",
        "full_desc": "Full basketball court construction with premium acrylic surfaces, professional ring installations and FIBA-standard line markings.",
        "icon": "Dribbble",
        "image": "https://images.unsplash.com/photo-1536578524251-eff3c73e9207?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "30-50 days", "starting_price": "Rp 450 jt",
        "materials": ["8-layer Acrylic Coating", "Cushioned Sub-base", "FIBA Standard Rings", "Glass Backboards"],
        "workflow": ["Concrete Slab", "Crack Repair", "Primer Layer", "Acrylic Coating", "Line Marking", "Ring Installation"],
        "features": ["FIBA approved", "8-year warranty", "Cushioned surface", "UV-resistant coating"],
        "order_idx": 3,
    },
    {
        "slug": "tennis", "title": "Tennis Court",
        "short_desc": "ITF-standard tennis court construction with hard, clay or acrylic surfaces.",
        "full_desc": "Tournament-grade tennis court construction with ITF-approved materials, professional net systems, and proper drainage.",
        "icon": "CircleDot",
        "image": "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "40-60 days", "starting_price": "Rp 550 jt",
        "materials": ["Acrylic Hard Court", "Tournament Net System", "Galvanized Posts", "Sub-base Drainage"],
        "workflow": ["Site Grading", "Drainage", "Base Construction", "Surface Coating", "Net & Posts", "Markings"],
        "features": ["ITF certified", "10-year structure", "All-weather", "Tournament ready"],
        "order_idx": 4,
    },
    {
        "slug": "volleyball", "title": "Volleyball Court",
        "short_desc": "Indoor/outdoor volleyball court construction with sport-specific surfaces.",
        "full_desc": "Complete volleyball facility with FIVB-standard surfaces, professional net systems and ideal court dimensions.",
        "icon": "Volleyball",
        "image": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "25-40 days", "starting_price": "Rp 280 jt",
        "materials": ["PU Sports Flooring", "Sand Court Setup", "FIVB Net System", "Boundary Lines"],
        "workflow": ["Layout Planning", "Base Preparation", "Surface Install", "Net Setup", "Line Painting"],
        "features": ["FIVB standard", "Shock absorbing", "5-year warranty", "Multi-court option"],
        "order_idx": 5,
    },
    {
        "slug": "running-track", "title": "Running Track",
        "short_desc": "IAAF-certified athletic running track installation with polyurethane surface.",
        "full_desc": "Professional athletic running tracks with IAAF-approved PU surfaces, full markings and stadium-grade construction.",
        "icon": "Activity",
        "image": "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "60-90 days", "starting_price": "Rp 1.2 M",
        "materials": ["13mm PU Spray Coat", "Sandwich PU System", "EPDM Granules", "IAAF Markings"],
        "workflow": ["Asphalt Base", "Quality Test", "PU Application", "Top Coat", "Lane Marking", "Certification"],
        "features": ["IAAF Class 1", "Olympic-grade", "Shock absorption 35-50%", "15-year lifespan"],
        "order_idx": 6,
    },
    {
        "slug": "synthetic-grass", "title": "Synthetic Grass",
        "short_desc": "High-quality synthetic grass installation for sports & landscape applications.",
        "full_desc": "Premium synthetic turf installation for football fields, golf, landscape, and recreational areas with various pile heights.",
        "icon": "Sprout",
        "image": "https://images.unsplash.com/photo-1622460132742-d218ff93958d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "20-40 days", "starting_price": "Rp 180 rb/m²",
        "materials": ["50mm Premium Turf", "Silica Sand Infill", "SBR Rubber Granules", "Geotextile Base"],
        "workflow": ["Ground Prep", "Edge Setup", "Turf Roll-out", "Seaming", "Infill Spread", "Brushing"],
        "features": ["UV stabilized", "Drainage 60L/min/m²", "Lead-free", "8-year warranty"],
        "order_idx": 7,
    },
    {
        "slug": "acrylic-flooring", "title": "Acrylic Sports Flooring",
        "short_desc": "Premium acrylic coating systems for multi-sport courts.",
        "full_desc": "Multi-layer acrylic sports flooring systems suitable for basketball, tennis, badminton and multi-purpose courts.",
        "icon": "Layers",
        "image": "https://images.unsplash.com/photo-1574629810360-7efbbe195018?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "duration": "15-30 days", "starting_price": "Rp 250 rb/m²",
        "materials": ["Acrylic Resurfacer", "Color Coating", "Texture Coating", "Line Paint"],
        "workflow": ["Surface Prep", "Crack Fill", "Resurfacer", "Color Layers", "Line Marking"],
        "features": ["8-layer system", "UV resistant", "Anti-slip", "Custom colors"],
        "order_idx": 8,
    },
]


PROJECTS_SEED = [
    {
        "title": "Jakarta International Mini Soccer Arena", "category": "mini-soccer",
        "location": "Jakarta Selatan", "surface_type": "FIFA Quality Synthetic Turf 50mm",
        "area_size": "1,200 m²", "completion_year": 2024,
        "description": "Premium mini soccer facility featuring FIFA-quality turf, LED stadium lighting, and advanced drainage system for year-round playability.",
        "cover_image": "https://images.unsplash.com/photo-1546717003-caee5f93a9db?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": [
            "https://images.unsplash.com/photo-1546717003-caee5f93a9db?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1622460132742-d218ff93958d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "before_image": "https://images.unsplash.com/photo-1581094271901-8022df4466f9?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "after_image": "https://images.unsplash.com/photo-1546717003-caee5f93a9db?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": True, "status": "completed",
    },
    {
        "title": "Surabaya Basketball Complex", "category": "basketball",
        "location": "Surabaya", "surface_type": "8-Layer Acrylic Sports Coating",
        "area_size": "608 m²", "completion_year": 2024,
        "description": "FIBA-standard basketball complex with cushioned acrylic surface, professional ring systems, and tournament-grade line markings.",
        "cover_image": "https://images.unsplash.com/photo-1536578524251-eff3c73e9207?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": [
            "https://images.unsplash.com/photo-1536578524251-eff3c73e9207?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
            "https://images.unsplash.com/photo-1600534220378-df36338afc40?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        ],
        "before_image": "https://images.unsplash.com/photo-1574629810360-7efbbe195018?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "after_image": "https://images.unsplash.com/photo-1536578524251-eff3c73e9207?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "featured": True, "status": "completed",
    },
    {
        "title": "Bandung Futsal Arena Premier", "category": "futsal",
        "location": "Bandung", "surface_type": "Vinyl Sports Flooring 6mm",
        "area_size": "800 m²", "completion_year": 2023,
        "description": "Indoor futsal facility with AMF-certified vinyl flooring, professional goal systems, and integrated LED lighting.",
        "cover_image": "https://images.unsplash.com/photo-1550881111-7cfde14b8073?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1550881111-7cfde14b8073?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": True, "status": "completed",
    },
    {
        "title": "Bali Athletic Running Track", "category": "running-track",
        "location": "Denpasar, Bali", "surface_type": "13mm PU Sandwich System",
        "area_size": "4,800 m² (400m track)", "completion_year": 2024,
        "description": "IAAF Class 1 certified running track with 8 lanes, full field events markings, and Olympic-grade polyurethane surface.",
        "cover_image": "https://images.unsplash.com/photo-1571008887538-b36bb32f4571?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1571008887538-b36bb32f4571?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": True, "status": "completed",
    },
    {
        "title": "Medan Tennis Center", "category": "tennis",
        "location": "Medan", "surface_type": "Acrylic Hard Court ITF",
        "area_size": "650 m² × 4 courts", "completion_year": 2023,
        "description": "Tournament-grade tennis center featuring 4 ITF-certified hard courts with professional net systems and spectator areas.",
        "cover_image": "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": False, "status": "completed",
    },
    {
        "title": "Yogyakarta Multi-Sport Complex", "category": "synthetic-grass",
        "location": "Yogyakarta", "surface_type": "Premium Monofilament Turf",
        "area_size": "2,400 m²", "completion_year": 2024,
        "description": "Multi-functional sports complex with synthetic grass football pitch and integrated training facilities.",
        "cover_image": "https://images.unsplash.com/photo-1622460132742-d218ff93958d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1622460132742-d218ff93958d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": True, "status": "completed",
    },
    {
        "title": "Semarang Volleyball Center", "category": "volleyball",
        "location": "Semarang", "surface_type": "PU Sports Flooring",
        "area_size": "324 m² × 2 courts", "completion_year": 2023,
        "description": "FIVB-standard volleyball facility with shock-absorbing PU surface and tournament net systems.",
        "cover_image": "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": False, "status": "completed",
    },
    {
        "title": "Makassar Sports Pavilion", "category": "acrylic-flooring",
        "location": "Makassar", "surface_type": "Multi-sport Acrylic Coating",
        "area_size": "1,500 m²", "completion_year": 2024,
        "description": "Multi-purpose pavilion with versatile acrylic flooring system for basketball, badminton, and volleyball.",
        "cover_image": "https://images.unsplash.com/photo-1574629810360-7efbbe195018?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "gallery": ["https://images.unsplash.com/photo-1574629810360-7efbbe195018?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600"],
        "featured": False, "status": "in-progress",
    },
]


TESTIMONIALS_SEED = [
    {
        "name": "Bapak Ahmad Hidayat", "role": "Direktur", "company": "PT Bumi Sportindo",
        "avatar": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?crop=entropy&cs=srgb&fm=jpg&q=85&w=400",
        "message": "Laksono Kontraktor menyelesaikan proyek mini soccer kami dengan kualitas world-class. Timeline tepat waktu, hasil akhir luar biasa, dan kualitas turf-nya benar-benar premium.",
        "rating": 5, "project_type": "Mini Soccer",
    },
    {
        "name": "Mrs. Sarah Wijaya", "role": "Facility Manager", "company": "Senayan Sports Complex",
        "avatar": "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?crop=entropy&cs=srgb&fm=jpg&q=85&w=400",
        "message": "Profesionalisme tim sangat tinggi. Kami menggunakan jasa mereka untuk lapangan basket dan tenis, dan hasilnya sesuai standar internasional.",
        "rating": 5, "project_type": "Basketball & Tennis",
    },
    {
        "name": "Bapak Reza Pratama", "role": "Owner", "company": "Pratama Futsal Bandung",
        "avatar": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?crop=entropy&cs=srgb&fm=jpg&q=85&w=400",
        "message": "Sudah 3 lokasi futsal kami dibangun oleh Laksono. Konsistensi kualitas dan layanan after-sales-nya membuat kami selalu kembali.",
        "rating": 5, "project_type": "Futsal",
    },
    {
        "name": "Ibu Devi Kartika", "role": "Project Manager", "company": "Kota Bali Athletic Foundation",
        "avatar": "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?crop=entropy&cs=srgb&fm=jpg&q=85&w=400",
        "message": "Running track kami mendapat sertifikasi IAAF berkat ketelitian Laksono Kontraktor. Sangat direkomendasikan untuk proyek atletik profesional.",
        "rating": 5, "project_type": "Running Track",
    },
]


BLOG_SEED = [
    {
        "slug": "panduan-memilih-rumput-sintetis",
        "title": "Panduan Lengkap Memilih Rumput Sintetis untuk Lapangan Sepak Bola",
        "excerpt": "Pelajari faktor penting dalam memilih rumput sintetis berkualitas tinggi: pile height, infill, dan sertifikasi FIFA.",
        "content": "Memilih rumput sintetis yang tepat adalah kunci performa lapangan sepak bola modern.\n\nPile height ideal untuk lapangan sepak bola adalah 50-60mm dengan monofilament yarn yang tahan UV. Sertifikasi FIFA Quality dan FIFA Quality Pro menjamin kualitas internasional. Sistem infill yang baik menggunakan kombinasi silica sand dan SBR rubber granules untuk shock absorption optimal.",
        "cover_image": "https://images.unsplash.com/photo-1622460132742-d218ff93958d?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "category": "Material Guide", "tags": ["synthetic grass", "soccer", "material"],
        "author": "Tim Engineering Laksono",
        "seo_title": "Panduan Rumput Sintetis FIFA Quality - Laksono Kontraktor",
        "seo_description": "Tips memilih rumput sintetis berkualitas FIFA untuk lapangan sepak bola.",
        "published": True,
    },
    {
        "slug": "perbandingan-lantai-olahraga-akrilik",
        "title": "Perbandingan Sistem Lantai Akrilik untuk Lapangan Basket",
        "excerpt": "Cushioned vs hard acrylic system: mana yang terbaik untuk lapangan basket Anda?",
        "content": "Sistem lantai akrilik memiliki beberapa varian dengan keunggulan masing-masing.\n\nCushioned acrylic system menyediakan shock absorption 8-12% yang ideal untuk pemain. Hard acrylic system memberi respon bola yang lebih cepat dan cocok untuk kompetisi resmi. Sertifikasi FIBA dan ITF menjamin spesifikasi internasional.",
        "cover_image": "https://images.unsplash.com/photo-1574629810360-7efbbe195018?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "category": "Comparison", "tags": ["acrylic", "basketball", "flooring"],
        "author": "Tim Engineering Laksono",
        "seo_title": "Perbandingan Lantai Akrilik Basket - Laksono Kontraktor",
        "seo_description": "Pilihan sistem lantai akrilik terbaik untuk lapangan basket profesional.",
        "published": True,
    },
    {
        "slug": "maintenance-lapangan-futsal",
        "title": "Tips Perawatan Lapangan Futsal Agar Tahan Lama",
        "excerpt": "Maintenance rutin lapangan futsal yang membuat lifespan investasi Anda lebih panjang.",
        "content": "Perawatan rutin adalah kunci memperpanjang usia lapangan futsal Anda.\n\nLakukan pembersihan harian dengan brushing lembut, recoating setiap 3-5 tahun, dan inspeksi struktural setiap 6 bulan. Hindari penggunaan sepatu non-sport dan benda tajam.",
        "cover_image": "https://images.unsplash.com/photo-1550881111-7cfde14b8073?crop=entropy&cs=srgb&fm=jpg&q=85&w=1600",
        "category": "Maintenance", "tags": ["futsal", "maintenance", "tips"],
        "author": "Tim Engineering Laksono",
        "seo_title": "Tips Maintenance Lapangan Futsal - Laksono Kontraktor",
        "seo_description": "Panduan perawatan lapangan futsal profesional.",
        "published": True,
    },
]
